# Generated by Django 4.0 on 2024-11-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicApp', '0003_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
