# Generated by Django 4.0 on 2024-12-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicApp', '0004_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
