# Generated by Django 4.0 on 2024-12-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicApp', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
